# log config
logging:
  config:
    classpath: logback.xml

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

free-api:
  poems: https://v1.alapi.cn/api/shici

xxl:
  job:
    # 执行器通讯TOKEN [选填]：非空时启用；
    access-token:
    executor:
      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      app-name: spring-boot-demo-task-xxl-job-executor
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 8090
      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      log-path: logs/spring-boot-demo-task-xxl-job/task-log
      # 执行器日志保存天数 [选填] ：值大于3时生效，启用执行器Log文件定期清理功能，否则不生效；
      log-retention-days: -1

justauth:
  type:
    GITEE:
      client-id: ENC(bXz07fs2NHON8GvzvMeezwKZQoKlNH657sK+suX/VCkf5jIjNHus1hR8AXZtIWxvU9ZD+ftcSVo1itgzECiLCQQovwzmwr0uYhX/Uziyq9oK7Y6QWsrWQj/TKSrHKTlMGxeNyvvurbiHVlTgEfrG+A==)
      client-secret: ENC(32DFX7H1gHeogJFAsSj0PkuJJw2ZfxWVRQZ3KNf9Hk0BoejPL9VPvdwkYXxCqR+PtiSU7XfBgH9rPH9TUW5pE00A1ocAEpQii8+BG0qppkDIHE8YOjbzCp6gDElPKmCElyZDBBcucv6gbN7rgrIsxw==)
      email: ENC(yvipFV7I83uXdPNEVjh+f7AfZrqze66YITAl3JnhKzwnmmtffqtt0UUTqWe90brm7Xq2TaOyekVwz9CkaFLzQw==)
      password: ENC(dRnK8CE5bZ3YDANzM/YVKY+nDihHZDgt3OablOM0jtu6gsO1lOLj5f9R1IJm+wk3)
